FROM postgres:16-alpine

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV PGDATA=/var/lib/postgresql/data/pgdata

EXPOSE 5432

COPY ./init.sql /docker-entrypoint-initdb.d/